### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#22]
### Description

You should be able to accumulate currency based on the value of an enemy upon its death. 

### Done Criteria

- [x] Total currency increased on death of an enemy according to the value of that enemy
- [x] Currency is displayed (in a basic manner) on the screen

**Comment by DerrekNguyen** [comment]
Currency implemented. Variable is called 'totalCurrency' and is increased every time an enemy dies by their respective 'currency' value.
Health implemented. Variable is called 'totalHealth' and is depleted every time an enemy reaches the end by their repective 'damage' value.
