### ISSUE TITLE
Scaffold base 3 enemy types

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#28]
### Description

Create 3 base enemy types (normal, speed and tank) either through inheritance, enum + constructor, or some otherm ethod.

### Done Criteria

- [x] Can instantiate a normal, speed or tank enemy and have them move along the path
- [x] The enemies are instantiated with their proper attributes (E.G. tank enemy has high health, slow speed and medium/high damage)

**Comment by DerrekNguyen** [comment]
3 basic enemy types are implemented. They are created through enum + constructor with their respective attributes. They are the 3 enemies on the main game at the moment.
