### ISSUE TITLE
Sequential wave spawning

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#37]
### Description

- Figure out a way to aggregate waves together to form an entire level
- Implement "breaks" in between waves

### Done Criteria

- [x]  Waves can be aggregated and spawned sequentially
- [ ]  The code structure is set up to implement breaks in between the waves

**Comment by DerrekNguyen** [comment]
Number of waves and enemies can be specified to form an entire level. 
Implemented using a button right now, when that button is pressed a new wave spawns.
Branch is called "sequential-wave" and uses the new curve path system.
