### ISSUE TITLE
Enemy pathing

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#38]
### Description

Fix the enemy pathing to more accurately follow the path. Make it relative to the window.

### Done Criteria

- [x] Enemies follow the path from start to finish without ever moving off the path

**Comment by DerrekNguyen** [comment]
A new path is created using the old grid system. Enemy follows this path correctly without any problems. Branch is called "path-fix-grid". 
Looked into a way to use a curve function to change the y-coordinate accordingly. This branch is called "path-fix-curve", it seems to work but still need more testing. Will attempt to merge if given permission.
