### ISSUE TITLE
Block tower placement upon paths

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#46]
### Description

Prevent a tower from being place upon path. Possibily use Derrek's curved path system to create to curved lines around the path and check if placement is within the y bounds of each path?

### Done Criteria

- [x] A tower cannot be placed upon any part of the path, but it can outside of it

**Comment by DerrekNguyen** [comment]
If you decide to work on this please let me know I will give you the curve functions for the path.
