### ISSUE TITLE
Randomize enemy movement

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#52]
### Description

Randomize the movement of enemies within set bounds to prevent overlap

### Done Criteria

- [x] Enemies move in a randomized manner that does not stray too far off the path the entire way along the path

**Comment by DerrekNguyen** [comment]
Enemies now has a fixed amount of offset that is constant at creation. Only affects where they are height-wise, and they never go off bound. 

branch is random-path
