### ISSUE TITLE
Modify wave system to allow spawning same enemy type multiple times

### ISSUE THREAD

**Issue by dominicf2001** [dominicf2001/project-beta#97]
### Description

We want to make it so you can spawn the same enemy type multiple times at varying quantities for each wave

### Done Criteria

- [x] You are able to specify in the wave data the same enemy type multiple times at varying quanties

**Comment by DerrekNguyen** [comment]
Changed the wave system to a 3d matrix. Will elaborate more in person
branch is wave-multiple.
